import { readFile, writeFile } from "node:fs/promises";
const source = await readFile(
  "Ricochet Robots/src/view/GameBoard.java",
  "utf8",
);
const barriers = [
  ...source.matchAll(
    /new Barrier\((\d+),\s*(\d+),\s*(\d+),\s*(\d+), ID.Barrier\)/g,
  ),
].map((m) => m.slice(1).map(Number));
const tokens = [
  ...source.matchAll(
    /new Token\((\d+),\s*(\d+),\s*28,\s*28, ID.Token\d+,\s*(\d+)\)/g,
  ),
]
  .map((m) => ({
    x: Math.floor(Number(m[1]) / 37),
    y: Math.floor(Number(m[2]) / 37),
    number: Number(m[3]),
    robot: (Number(m[3]) - 1) % 4,
  }))
  .filter((t) => t.number <= 16);
const walls = barriers
  .filter(([x, y, w, h]) => (w === 6 && h === 36) || (w === 36 && h === 6))
  .map(([x, y, w]) => ({
    x: Math.round(x / 37),
    y: Math.round(y / 37),
    axis: w === 6 ? "v" : "h",
  }));
if (tokens.length !== 16 || walls.length !== 38)
  throw new Error(
    "Standard Java board layout changed; review the grid translation.",
  );
const board = {
  size: 16,
  blocked: [
    [7, 7],
    [8, 7],
    [7, 8],
    [8, 8],
  ],
  walls,
  tokens,
};
const output =
  "// Standard GameBoard.java snapped to its 37-pixel grid. Generated by scripts/sync-board.mjs.\nexport const BOARD=" +
  JSON.stringify(board, null, 2) +
  ";\n";
if (process.argv.includes("--check")) {
  if ((await readFile("demo/board.js", "utf8")) !== output)
    throw new Error(
      "Run node scripts/sync-board.mjs and review the board changes.",
    );
} else await writeFile("demo/board.js", output);
