// Standard GameBoard.java snapped to its 37-pixel grid. Generated by scripts/sync-board.mjs.
export const BOARD={
  "size": 16,
  "blocked": [
    [
      7,
      7
    ],
    [
      8,
      7
    ],
    [
      7,
      8
    ],
    [
      8,
      8
    ]
  ],
  "walls": [
    {
      "x": 2,
      "y": 0,
      "axis": "v"
    },
    {
      "x": 0,
      "y": 6,
      "axis": "h"
    },
    {
      "x": 0,
      "y": 12,
      "axis": "h"
    },
    {
      "x": 7,
      "y": 15,
      "axis": "v"
    },
    {
      "x": 15,
      "y": 11,
      "axis": "h"
    },
    {
      "x": 15,
      "y": 4,
      "axis": "h"
    },
    {
      "x": 1,
      "y": 2,
      "axis": "h"
    },
    {
      "x": 2,
      "y": 2,
      "axis": "v"
    },
    {
      "x": 3,
      "y": 6,
      "axis": "v"
    },
    {
      "x": 4,
      "y": 1,
      "axis": "v"
    },
    {
      "x": 7,
      "y": 3,
      "axis": "v"
    },
    {
      "x": 6,
      "y": 4,
      "axis": "h"
    },
    {
      "x": 9,
      "y": 3,
      "axis": "h"
    },
    {
      "x": 10,
      "y": 2,
      "axis": "v"
    },
    {
      "x": 12,
      "y": 0,
      "axis": "v"
    },
    {
      "x": 13,
      "y": 1,
      "axis": "h"
    },
    {
      "x": 13,
      "y": 1,
      "axis": "v"
    },
    {
      "x": 14,
      "y": 5,
      "axis": "v"
    },
    {
      "x": 14,
      "y": 6,
      "axis": "h"
    },
    {
      "x": 11,
      "y": 6,
      "axis": "h"
    },
    {
      "x": 12,
      "y": 6,
      "axis": "v"
    },
    {
      "x": 1,
      "y": 10,
      "axis": "h"
    },
    {
      "x": 2,
      "y": 9,
      "axis": "v"
    },
    {
      "x": 4,
      "y": 11,
      "axis": "h"
    },
    {
      "x": 4,
      "y": 10,
      "axis": "v"
    },
    {
      "x": 3,
      "y": 14,
      "axis": "h"
    },
    {
      "x": 3,
      "y": 14,
      "axis": "v"
    },
    {
      "x": 5,
      "y": 13,
      "axis": "h"
    },
    {
      "x": 6,
      "y": 13,
      "axis": "v"
    },
    {
      "x": 8,
      "y": 10,
      "axis": "h"
    },
    {
      "x": 9,
      "y": 10,
      "axis": "v"
    },
    {
      "x": 14,
      "y": 10,
      "axis": "h"
    },
    {
      "x": 14,
      "y": 9,
      "axis": "v"
    },
    {
      "x": 13,
      "y": 12,
      "axis": "h"
    },
    {
      "x": 13,
      "y": 11,
      "axis": "v"
    },
    {
      "x": 10,
      "y": 13,
      "axis": "h"
    },
    {
      "x": 10,
      "y": 13,
      "axis": "v"
    },
    {
      "x": 12,
      "y": 15,
      "axis": "v"
    }
  ],
  "tokens": [
    {
      "x": 9,
      "y": 2,
      "number": 1,
      "robot": 0
    },
    {
      "x": 1,
      "y": 2,
      "number": 2,
      "robot": 1
    },
    {
      "x": 8,
      "y": 10,
      "number": 3,
      "robot": 2
    },
    {
      "x": 3,
      "y": 14,
      "number": 4,
      "robot": 3
    },
    {
      "x": 1,
      "y": 9,
      "number": 5,
      "robot": 0
    },
    {
      "x": 13,
      "y": 11,
      "number": 6,
      "robot": 1
    },
    {
      "x": 4,
      "y": 1,
      "number": 7,
      "robot": 2
    },
    {
      "x": 11,
      "y": 6,
      "number": 8,
      "robot": 3
    },
    {
      "x": 3,
      "y": 6,
      "number": 9,
      "robot": 0
    },
    {
      "x": 4,
      "y": 10,
      "number": 10,
      "robot": 1
    },
    {
      "x": 13,
      "y": 1,
      "number": 11,
      "robot": 2
    },
    {
      "x": 14,
      "y": 9,
      "number": 12,
      "robot": 3
    },
    {
      "x": 10,
      "y": 13,
      "number": 13,
      "robot": 0
    },
    {
      "x": 14,
      "y": 5,
      "number": 14,
      "robot": 1
    },
    {
      "x": 5,
      "y": 13,
      "number": 15,
      "robot": 2
    },
    {
      "x": 6,
      "y": 3,
      "number": 16,
      "robot": 3
    }
  ]
};
